#!/system/xbin/bash
clear
echo "\033[32;1m"Telegram : https://t.me/enzomes1234"
"YouTube : [ E n z o m e s ]
sleep 1
echo "PUBG MOBILE SEASON 11 FREE UC 10000 30000 50000 80000 UC FREE HACK"
sleep 1 
echo "ТА PUBG MOBILE ACCOUNT ИЙНХАА ID ГАА ХИЙН ҮҮ !"
read p;
sleep 1 
echo "10000 UC [1]"
echo "30000 UC [2]"
echo "50000 UC [3]"
echo "80000 UC [4]"
echo " Сонголтоо бич нүү !"
read p;
sleep 1 
echo "PID TTY          TIME CMD
 8950 pts/4    00:00:00 bash
 8958 pts/4    00:00:00 ps"
sleep 1
sleep 2
echo "PID TTY          TIME CMD
 8950 pts/4    00:00:00 bash
 8958 pts/4    00:00:00 ps"
sleep 1
sleep 2
echo "internal/0/Android/obb/com.tencent.ig
sleep 1
sleep 2
sleep 3
/attacking/main.11460.com.tencent.ig.obb/renailling/on.off.hash.127.0.0.1/tencent/admin/attack/paypal/password/hacking/playstore/services/no
sleep 1 
sleep 2
/accesgranted/succesfull"
echo "22%"
sleep 3
echo "33%"
sleep 3
echo "56%"
sleep 3
echo "100%"
sleep 1
echo "internal/0/Android/obb/com.tencent.ig/attacking/main.11460.com.tencent.ig.obb/renailling/on.off.hash.127.0.0.1/tencent/admin/attack/paypal/password/hacking/playstore/services/no/accesgranted/succesfull"
sleep 1
sleep 2
sleep 3
sleep 4
sleep 5
echo "PING facebook.com (157.240.15.35) 56(84) bytes of data.
sleep 1
sleep 2
sleep 3
sleep 4
sleep 5
64 bytes from  (157.240.15.35): icmp_seq=1 ttl=51 time=77.6 ms
sleep 1
157.240.15.35): icmp_seq=7 ttl=51 time=126 ms
64 bytes from edge-star-mini-shv-02-hkg3.fa (15
sleep 1
7.240.15.35): icmp_seq=8 ttl=51 time=87 ms
64 bytes fr edge-star-mini-shv-02-hkg3.fm (157.
sleep 1
240.15.35): icmp_seq=9 ttl=51 time=83.7 ms
64  (157.240.15.35): icmp_seq=10 ttl=51 time=81.2 ms
64 b
sleep 1
ytes  (157.240.15.35): icmp_seq=11 ttl=51 time=79.3 ms
64 bytes from edge-star-mini-shv-02-hkg3. (157
sleep 1
.240.15.35): icmp_seq=12 ttl=51 time=78.5 ms
64 edge-star-mini-shv-02-hkg3com (157.240.15.35): icmp_seq=13 ttl=51 time=96.6 ms
64 
sleep 1
bytes from  (157.240.15.35): icmp_seq=14 ttl=51 time=136 ms
64 bytes  (157.240.15.35): icmp_seq=15 ttl=51 t184 ms
64
sleep 1
 bytes fro edge-star-mini-shv-02-hkgk.com (157.240.15.35): icmp_seq=16 ttl=51 time=91.6 ms
sleep 1
157.240.15.35): icmp_seq=17 ttl=51 time=89.6 ms
64 bytes from edge-star-mini-shv-02- (157.240.15.35): ic
sleep 1
mp_seq=18 ttl=51 t88.8 ms
sleep 1
  (157.240.15.35): icmp_seq=19 ttl=51 t88. ms
m (157.240.15.35): icmp_seq=20 ttl=51 time=87.7 ms
64 bytes  (157.240.15.35): icmp_seq=21 ttl=51 tim=84.1 sleep 1
 (157.240.15.35): icmp_seq=22 ttl=51 time=103 ms
64 bytes from edge-star-mini-sh (157.240.15.35): icmp_seq=23 ttl=51 time=102 ms"
sleep 1
echo "Succesfully hacked enzomes admin ТА pubg руугаа орно уу !"





 